In [1]:
#how to read numpy values
import numpy as np
cvalues = [20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]
c=np.array(cvalues)
print(c)

[20.1 20.8 21.9 22.5 22.7 22.3 21.8 21.2 20.9 20.1]


In [5]:
#Print algebric expression in numpy values(celcius to farenheit) & type of data
import numpy as np
cvalues = [20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]
c=np.array(cvalues)
print((c*9/5)+32)
type(c)

[68.18 69.44 71.42 72.5  72.86 72.14 71.24 70.16 69.62 68.18]


numpy.ndarray

In [13]:
#Arange in numpy
import numpy as np
a = np.arange(1, 10)
print(a)

#iterator program
x=range(1,10)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)


In [23]:
#rounding values using numpy
import numpy as np
x=np.arange(1.2,2.2,3.4,int)
print(x)

[1]


In [45]:
#equally spaced values as output
import numpy as np
print(np.linspace(1, 100, 10))
print(np.linspace(1, 100, 10,endpoint=False))


[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
[ 1.  10.9 20.8 30.7 40.6 50.5 60.4 70.3 80.2 90.1]


In [41]:
#equally spaced values as output and find out the adjacent value
import numpy as np
print(np.linspace(1, 100, 5,retstep=True))

(array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ]), np.float64(24.75))
